apiVersion: v1
data:
  traefik.toml: "defaultEntryPoints = [\"http\",\"https\"]\ndebug = false\nlogLevel
    = \"INFO\"\n\nInsecureSkipVerify = true\n[entryPoints]\n  [entryPoints.http]\n
    \ address = \":80\"\n  compress = true\n  [entryPoints.https]\n  address = \":443\"\n
    \   [entryPoints.https.tls]\n    \n[api]\n  [api.statistics]\n    recentErrors
    = 10\n    \n[web]\n  address = \":8080\"\n  \n[kubernetes]\n  labelselector =
    \"zone=internal\"\n\n[ping]\nentryPoint = \"http\"\n\n[accessLog]\n"
kind: ConfigMap
metadata:
  creationTimestamp: 2018-11-20T09:23:18Z
  name: cm-internal-traefik
  namespace: kube-system
  resourceVersion: "3356086"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cm-internal-traefik
  uid: eac46b0d-eca5-11e8-afd0-005056880c0c
