apiVersion: v1
data:
  traefik.toml: "defaultEntryPoints = [\"http\",\"https\"]\ndebug = false\nlogLevel
    = \"INFO\"\n\nInsecureSkipVerify = true\n[entryPoints]\n  [entryPoints.http]\n
    \ address = \":80\"\n  compress = true\n  [entryPoints.https]\n  address = \":443\"\n
    \   [entryPoints.https.tls]\n    \n[api]\n  [api.statistics]\n    recentErrors
    = 10\n    \n[web]\n  address = \":8080\"\n  \n[kubernetes]\n  labelselector =
    \"zone=internal\"\n\n[ping]\nentryPoint = \"http\"\n\n[accessLog]\n"
kind: ConfigMap
metadata:
  name: cm-internal-traefik
  namespace: kube-system
