apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: 2018-11-20T09:40:43Z
  name: crb-internal-traefik
  resourceVersion: "3357717"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/crb-internal-traefik
  uid: 597051bb-eca8-11e8-afd0-005056880c0c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-internal-traefik
subjects:
- kind: ServiceAccount
  name: sa-internal-traefik
  namespace: kube-system
