apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/redirect-entry-point: http
  labels:
    zone: external
  name: ing-httpd
  namespace: test-customer
spec:
  rules:
  - host: testweb-w1.benestra.sk
    http:
      paths:
      - backend:
          serviceName: tc-httpd
          servicePort: 80
        path: /
  - host: testweb-w2.benestra.sk
    http:
      paths:
      - backend:
          serviceName: tc-httpd
          servicePort: 80
        path: /
status:
  loadBalancer: {}
