apiVersion: v1
data:
  traefik.toml: "defaultEntryPoints = [\"http\",\"https\"]\ndebug = false\nlogLevel
    = \"INFO\"\n\n[entryPoints]\n  [entryPoints.http]\n    address = \":80\"\n    compress
    = true\n    [entryPoints.https]\n    address = \":443\"\n    compress = true\n
    \   [entryPoints.https.tls]\n    \n[api]\n  [api.statistics]\n    recentErrors
    = 10\n    \n[kubernetes]\n  labelselector = \"zone=external\"\n  \n[ping]\n  entryPoint
    = \"http\"\n\n[accessLog]\n\n[acme]\n  email = \"acme@acme.com\"\n  storage =
    \"acme.json\"\n  acmeLogging = true\n  entryPoint = \"https\"\n  OnHostRule =
    true\n  #caServer = \"https://acme-staging-v02.api.letsencrypt.org/directory\"\n
    \ [acme.httpChallenge]\n    entryPoint=\"http\"\n"
kind: ConfigMap
metadata:
  name: cm-external-traefik
  namespace: kube-system
