apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-external-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-external-traefik
subjects:
- kind: ServiceAccount
  name: sa-external-traefik
  namespace: kube-system
