apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-internal-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-internal-traefik
subjects:
- kind: ServiceAccount
  name: sa-internal-traefik
  namespace: kube-system
