kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-external-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx-external
    app.kubernetes.io/part-of: ingress-nginx-external
