kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-internal-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx-internal
    app.kubernetes.io/part-of: ingress-nginx-internal
