apiVersion: v1
kind: Service
metadata:
  name: svc-external-ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx-external
    app.kubernetes.io/part-of: ingress-nginx-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx-external
    app.kubernetes.io/part-of: ingress-nginx-external
